In [15]:
import torch
import torchvision.transforms as tf
import albumentations
import cv2

# 0. Normal video cloning

In [16]:
import cv2

def read_and_write_video(input_video_path, output_video_path):
    """
    Reads a video from a file and writes it to another file in MP4 format.
    
    Args:
        input_video_path (str): Path to the input video file.
        output_video_path (str): Path to the output video file.
    """
    # Open the input video file
    cap = cv2.VideoCapture(input_video_path)
    # Get video properties
    fps = cap.get(cv2.CAP_PROP_FPS)
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))    
    # Create the video writer
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_video_path, fourcc, fps, (width, height))
    
    
    # Process each frame
    frame_count = 0
    while True:
        ret, frame = cap.read()
        if not ret:
            break
        # Write the frame to the output video
        out.write(frame)
        # Update the frame count
        frame_count += 1
    # Release the video capture and writer
    cap.release()
    out.release()
    # Get output video information
    out_cap = cv2.VideoCapture(output_video_path)
    out_cap.release()
    



# 1. Lower sharpness

In [17]:
import cv2
import torch
import torchvision.transforms as tf 

from torchvision.transforms.functional import adjust_sharpness

def reduce_sharpness(input_video_path, output_video_path, sharpness_factor = 0.5):
    """
    Reduces the sharpness of a video.
    
    Args:
        input_video_path (str): Path to the input video file.
        output_video_path (str): Path to the output video file.
        sharpness_factor (float, optional): Sharpness factor, ranging from 0 (blurred) to 2 (sharpened). Defaults to 0.5.
    """
    totensor = tf.ToTensor()
    # Load the video
    cap = cv2.VideoCapture(input_video_path)
    # Get video properties
    fps = cap.get(cv2.CAP_PROP_FPS)
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    # Create the video writer
    fourcc = cv2.VideoWriter_fourcc(*'mp4v') # correct format
    out = cv2.VideoWriter(output_video_path, fourcc, fps, (width, height))
    
    
    
    # Process each frame
    frame_count = 0
    for frame_count in range(total_frames):
        ret, frame = cap.read()
        if not ret:
            break
        # Convert the frame to a PyTorch tensor
        frame_tensor = totensor(frame)
        # Adjust the sharpness of the frame 
        adjusted_frame_tensor = adjust_sharpness(frame_tensor, sharpness_factor = 60)
        # Convert the adjusted frame back to a NumPy array
        adjusted_frame = (adjusted_frame_tensor.squeeze(0).permute(1, 2, 0) * 255).byte().numpy()
        # Write the adjusted frame to the output video
        out.write(adjusted_frame)
        frame_count += 1
        
    # Release the video capture and writer
    cap.release()
    out.release()
    
    # Print information about the output video after sharpness
    cv2.VideoCapture(output_video_path).release()
    cv2.destroyAllWindows()




In [18]:

reduce_sharpness('./videos/football.mp4','output/low_sharp.mp4')
# average augmentation time: 
# read_and_write_video('./videos/football.mp4','output/low_sharp.mp4')

frame:::  [[[153 123 135]
  [150 120 131]
  [139 109 122]
  ...
  [106  71  89]
  [106  71  89]
  [106  71  89]]

 [[153 123 135]
  [231 201 213]
  [ 99  69  81]
  ...
  [ 65  31  48]
  [ 65  31  48]
  [106  71  89]]

 [[153 123 135]
  [231 201 213]
  [ 99  69  81]
  ...
  [136 102 119]
  [136 102 119]
  [108  75  91]]

 ...

 [[144  94  95]
  [  0   0   0]
  [  0   0   0]
  ...
  [179  70  64]
  [122 103 129]
  [177  94  70]]

 [[139  89  91]
  [  0   0   0]
  [  0   0   0]
  ...
  [235 103  45]
  [179  98  36]
  [179  94  67]]

 [[134  83  86]
  [106  54  57]
  [ 89  37  40]
  ...
  [181  94  67]
  [179  94  67]
  [179  94  67]]]
frame:::  [[[127  96 108]
  [127  96 108]
  [127  96 108]
  ...
  [108  75  91]
  [108  75  91]
  [108  75  91]]

 [[127  96 108]
  [127  96 108]
  [127  96 108]
  ...
  [109  75  93]
  [109  75  93]
  [109  75  93]]

 [[127  96 108]
  [127  96 108]
  [127  96 108]
  ...
  [110  76  94]
  [110  76  94]
  [110  76  94]]

 ...

 [[123  72  75]
  [147  96  98]
